use_frameworks!

platform :ios, '9.0'

target 'PGCollectionViewFittedEndLineLayout_Example' do
  pod 'PGCollectionViewFittedEndLineLayout', :path => '../'

  target 'PGCollectionViewFittedEndLineLayout_Tests' do
    inherit! :search_paths

    
  end
end
